  <style>
    #contact_form{
      color:black;
      font-weight:bold;
      font-size:10px;
      width:480px;
      height:100px;
      padding-left:20px;
      padding-top:20px;

      /*border:solid red thin;*/
    }
    #contact_form .validate_field{
      border:dotted thin red; 
    }

    #contact_form input{
      width:160px;
    }

    #contact_form .column1{
      width:60px;
    }
    #contact_form .column2{
      width:160px;
    }
    #contact_form .column3{
      width:60px;
    }
    #contact_form .column4{
      width:160px;
    }

    #contact_form .send{
      font-weight:bold;
      font-size:12px;
      color:black;
    }
    #contact_form a{
      color:black;
    }

  </style>
  <div id="contact_form">
    <div id="send_success" style="display:none;text-align:center">
      Besten Dank
    </div>
    <!--
    <table border=0>
    -->
    <form id="send_form" action="send.php?page_id=<?php echo $this->page_id; ?>"  method="post">
    <table>
      <tr>
        <td class="column1">
            Vorname
        </td>
        <td class="column2">
            <input type="text"  name="firstname"/>
        </td>
        <td class="column3">
            Name
        </td>
        <td class="column4">
          <input type="text"  name="name"/>
        </td>
      </tr>
      <tr>
        <td>
            Adresse
        </td>
        <td>
            <input type="text"  name="address"/>
        </td>
        <td>
            PLZ
        </td>
        <td>
            <input type="text"  style="width:30px;" name="postcode" />
            Ort
            <input type="text"  style="width:110px;" name="city"/>
        </td>
      </tr>
      <tr>
        <td>
          Email
        </td>
        <td colspan="3">
          <input type="text"  style="width:300px" name="email" />
            <a href="#" onclick="send_form_submit();return false;">
              <span class="send">
                &nbsp;&nbsp;
                ABSENDEN
              </span>
            </a>
        </td>
      </tr>
    </table>
    </form>
  </div>

    function send_form_submit()
    {
      var elements=new Array('firstname','name','address','postcode','city','email');
      for(var i in elements)
      {
        if(jQuery("#send_form [name="+elements[i]+"]").val() == false)
        {
          jQuery("#send_form [name="+elements[i]+"]").addClass('validate_field'); 
          return false;
        }
      }


      FrdForm.selector="#send_form";
      FrdForm.dataType='html';
      FrdForm.success=function(data){

        var name='<?php echo $this->global->config['post_name']; ?>';
        var caption='<?php echo $this->global->config['post_caption']; ?>';
        var description='<?php echo $this->global->config['post_description']; ?>';
        var link='<?php echo $this->global->config['post_link']; ?>';
        var picture='<?php echo $this->global->config['post_picture']; ?>';

        fbPostToUserWall(name,caption,description,link,picture);

        jQuery("#send_form").hide();
        jQuery("#send_success").show();
        jQuery("#form_part").css('height','50');

      };
      FrdForm.ajaxSubmit();
    }

