<?
/*
	This File is Generated By EADS
	All Rights are Reserved By --------------
*/
/*
	Require Files
*/
require_once("clsGeneral.php");
/*
	Class
*/
class user
{
/*
	Attributes
*/
	 var $userid;
	 var $groupid;
	 var $name;
	 var $network;
	 var $age;
	 var $gender;
	 var $datetime;
	 var $status;
	 var $temp;
/*
	Constructor
*/
	function user()
	{
	$this->userid = -1;
	$this->groupid = -1;
	$this->name = "";
	$this->network = "";
	$this->age = "";
	$this->gender = "";
	$this->datetime = "";
	$this->status = -1;
	$this->temp = "";
	}
/*
	Update Function
*/
	function Update()
	{
	$this->name= replaceOps($this->name);
	$this->network= replaceOps($this->network);
	$this->age= replaceOps($this->age);
	$this->gender= replaceOps($this->gender);
	$this->datetime= replaceOps($this->datetime);
	$this->temp= replaceOps($this->temp);
	db_execute("UPDATE user SET  groupid = {$this->groupid} , name = '{$this->name}' , network = '{$this->network}' , age = '{$this->age}' , gender = '{$this->gender}' , datetime = '{$this->datetime}' , status = {$this->status} , temp = '{$this->temp}'  WHERE userid = {$this->userid}");
	}
}
/*
	This File is Generated By EADS
	All Rights are Reserved By ------------
*/
?>
