<?
/*
	This File is Generated By EADS
	All Rights are Reserved By ------------
*/
/*
	Require Files
*/
require_once("clsGeneral.php");
require_once("class.user.php");
/*
	Collection
*/
class Collectionuser
{
	function AddNew($object)
	{
	$object->name= replaceOps($object->name);
	$object->network= replaceOps($object->network);
	$object->age= replaceOps($object->age);
	$object->gender= replaceOps($object->gender);
	$object->datetime= replaceOps($object->datetime);
	$object->temp= replaceOps($object->temp);
	db_execute("INSERT INTO user Values('' , {$object->groupid}  , '{$object->name}'  , '{$object->network}'  , '{$object->age}'  , '{$object->gender}'  , '{$object->datetime}'  , {$object->status}  , '{$object->temp}'  )");
	}

	function RemoveByuserid($var)
	{
	db_execute("DELETE FROM user WHERE userid = $var");
	}
	function RemoveBygroupid($var)
	{
	db_execute("DELETE FROM user WHERE groupid = $var");
	}
	function RemoveByname($var)
	{
	db_execute("DELETE FROM user WHERE name = CONVERT( _utf8 '$var' USING latin1 ) COLLATE latin1_swedish_ci");
	}
	function RemoveBynetwork($var)
	{
	db_execute("DELETE FROM user WHERE network = CONVERT( _utf8 '$var' USING latin1 ) COLLATE latin1_swedish_ci");
	}
	function RemoveByage($var)
	{
	db_execute("DELETE FROM user WHERE age = CONVERT( _utf8 '$var' USING latin1 ) COLLATE latin1_swedish_ci");
	}
	function RemoveBygender($var)
	{
	db_execute("DELETE FROM user WHERE gender = CONVERT( _utf8 '$var' USING latin1 ) COLLATE latin1_swedish_ci");
	}
	function RemoveBydatetime($var)
	{
	db_execute("DELETE FROM user WHERE datetime = CONVERT( _utf8 '$var' USING latin1 ) COLLATE latin1_swedish_ci");
	}
	function RemoveBystatus($var)
	{
	db_execute("DELETE FROM user WHERE status = $var");
	}
	function RemoveBytemp($var)
	{
	db_execute("DELETE FROM user WHERE temp = CONVERT( _utf8 '$var' USING latin1 ) COLLATE latin1_swedish_ci");
	}
	function getAllusers()
	{
	$query = db_execute_return("SELECT * FROM user");
	if(mysql_num_rows($query)>0)
	{
	while($result = mysql_fetch_assoc($query))
	{
	 $object = new user();
	$object->userid = $result["userid"];
	$object->groupid = $result["groupid"];
	$object->name = $result["name"];
	$object->network = $result["network"];
	$object->age = $result["age"];
	$object->gender = $result["gender"];
	$object->datetime = $result["datetime"];
	$object->status = $result["status"];
	$object->temp = $result["temp"];
	$resultlist[$object->userid] = $object;
	}
	mysql_free_result($query);
	return $resultlist;
	}
	else
	return false;
	}

	function getuserByuserid($var)
	{
	$query = db_execute_return("SELECT * FROM user WHERE userid = $var");
	if(mysql_num_rows($query)>0)
	{
	$result = mysql_fetch_assoc($query);
	$object = new user();
	$object->userid = $result["userid"];
	$object->groupid = $result["groupid"];
	$object->name = $result["name"];
	$object->network = $result["network"];
	$object->age = $result["age"];
	$object->gender = $result["gender"];
	$object->datetime = $result["datetime"];
	$object->status = $result["status"];
	$object->temp = $result["temp"];
	mysql_free_result($query);
	return $object;
	}
	else
	return false;
	}

	function getusersBygroupid($var)
	{
	$query = db_execute_return("SELECT * FROM user WHERE groupid = $var");
	if(mysql_num_rows($query)>0)
	{
	while($result = mysql_fetch_assoc($query))
	{
	 $object = new user();
	$object->userid = $result["userid"];
	$object->groupid = $result["groupid"];
	$object->name = $result["name"];
	$object->network = $result["network"];
	$object->age = $result["age"];
	$object->gender = $result["gender"];
	$object->datetime = $result["datetime"];
	$object->status = $result["status"];
	$object->temp = $result["temp"];
	$resultlist[$object->userid] = $object;
	}
	mysql_free_result($query);
	return $resultlist;
	}
	else
	return false;
	}

	function getuserByname($var)
	{
	$query = db_execute_return("SELECT * FROM user WHERE name = '$var'");
	if(mysql_num_rows($query)>0)
	{
	$result = mysql_fetch_assoc($query);
	$object = new user();
	$object->userid = $result["userid"];
	$object->groupid = $result["groupid"];
	$object->name = $result["name"];
	$object->network = $result["network"];
	$object->age = $result["age"];
	$object->gender = $result["gender"];
	$object->datetime = $result["datetime"];
	$object->status = $result["status"];
	$object->temp = $result["temp"];
	mysql_free_result($query);
	return $object;
	}
	else
	return false;
	}

	function getusersBynetwork($var)
	{
	$query = db_execute_return("SELECT * FROM user WHERE network = '$var'");
	if(mysql_num_rows($query)>0)
	{
	while($result = mysql_fetch_assoc($query))
	{
	 $object = new user();
	$object->userid = $result["userid"];
	$object->groupid = $result["groupid"];
	$object->name = $result["name"];
	$object->network = $result["network"];
	$object->age = $result["age"];
	$object->gender = $result["gender"];
	$object->datetime = $result["datetime"];
	$object->status = $result["status"];
	$object->temp = $result["temp"];
	$resultlist[$object->userid] = $object;
	}
	mysql_free_result($query);
	return $resultlist;
	}
	else
	return false;
	}

	function getusersByage($var)
	{
	$query = db_execute_return("SELECT * FROM user WHERE age = '$var'");
	if(mysql_num_rows($query)>0)
	{
	while($result = mysql_fetch_assoc($query))
	{
	 $object = new user();
	$object->userid = $result["userid"];
	$object->groupid = $result["groupid"];
	$object->name = $result["name"];
	$object->network = $result["network"];
	$object->age = $result["age"];
	$object->gender = $result["gender"];
	$object->datetime = $result["datetime"];
	$object->status = $result["status"];
	$object->temp = $result["temp"];
	$resultlist[$object->userid] = $object;
	}
	mysql_free_result($query);
	return $resultlist;
	}
	else
	return false;
	}

	function getusersBygender($var)
	{
	$query = db_execute_return("SELECT * FROM user WHERE gender = '$var'");
	if(mysql_num_rows($query)>0)
	{
	while($result = mysql_fetch_assoc($query))
	{
	 $object = new user();
	$object->userid = $result["userid"];
	$object->groupid = $result["groupid"];
	$object->name = $result["name"];
	$object->network = $result["network"];
	$object->age = $result["age"];
	$object->gender = $result["gender"];
	$object->datetime = $result["datetime"];
	$object->status = $result["status"];
	$object->temp = $result["temp"];
	$resultlist[$object->userid] = $object;
	}
	mysql_free_result($query);
	return $resultlist;
	}
	else
	return false;
	}

	function getuserBydatetime($var)
	{
	$query = db_execute_return("SELECT * FROM user WHERE datetime = '$var'");
	if(mysql_num_rows($query)>0)
	{
	$result = mysql_fetch_assoc($query);
	$object = new user();
	$object->userid = $result["userid"];
	$object->groupid = $result["groupid"];
	$object->name = $result["name"];
	$object->network = $result["network"];
	$object->age = $result["age"];
	$object->gender = $result["gender"];
	$object->datetime = $result["datetime"];
	$object->status = $result["status"];
	$object->temp = $result["temp"];
	mysql_free_result($query);
	return $object;
	}
	else
	return false;
	}

	function getusersBystatus($var)
	{
	$query = db_execute_return("SELECT * FROM user WHERE status = $var");
	if(mysql_num_rows($query)>0)
	{
	while($result = mysql_fetch_assoc($query))
	{
	 $object = new user();
	$object->userid = $result["userid"];
	$object->groupid = $result["groupid"];
	$object->name = $result["name"];
	$object->network = $result["network"];
	$object->age = $result["age"];
	$object->gender = $result["gender"];
	$object->datetime = $result["datetime"];
	$object->status = $result["status"];
	$object->temp = $result["temp"];
	$resultlist[$object->userid] = $object;
	}
	mysql_free_result($query);
	return $resultlist;
	}
	else
	return false;
	}

	function getuserBytemp($var)
	{
	$query = db_execute_return("SELECT * FROM user WHERE temp = '$var'");
	if(mysql_num_rows($query)>0)
	{
	$result = mysql_fetch_assoc($query);
	$object = new user();
	$object->userid = $result["userid"];
	$object->groupid = $result["groupid"];
	$object->name = $result["name"];
	$object->network = $result["network"];
	$object->age = $result["age"];
	$object->gender = $result["gender"];
	$object->datetime = $result["datetime"];
	$object->status = $result["status"];
	$object->temp = $result["temp"];
	mysql_free_result($query);
	return $object;
	}
	else
	return false;
	}
}
/*
	This File is Generated By EADS
	All Rights are Reserved By ------------
*/
?>
